---

### EKINOPS ONEOS
- block:

  - include: checkrunningos.oneos.yml

  - include: "checkfileexists.oneos.yml"

  - include: validatefile.oneos.yml

  - include: checkdiskspace.oneos.yml
    when: bootfile_exists is false

  when: ansible_network_os == "oneos5" or ansible_network_os == "oneos6"


